targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      retrofit_generator:
        options:
          auto_generate: true
      injectable_generator:
        options:
          auto_generate: true
      freezed:
        options:
          auto_generate: true

